# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-10 05:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ot_app', '0002_weekend_weekend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weekend',
            name='saturday',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='weekend',
            name='sunday',
            field=models.CharField(max_length=255),
        ),
    ]
